version: '3.8'

services:
  web:
    build: .
    expose:
      - "5000"
    environment:
      - FLASK_APP=run.py
    depends_on:
      - rabbitmq
    env_file:
      - .env
    volumes:
      - ./jobs.db:/app/jobs.db
    ports:
      - "5000:5000"
  
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"

  worker:
    build: .
    command: python worker.py
    depends_on:
      - rabbitmq
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./jobs.db:/app/jobs.db

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./demo-frontend:/usr/share/nginx/html:ro
    depends_on:
      - web
